name: Update

on:
  push:
    branches:
      - master

jobs:
  list-update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Update Lists
      run: |
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv4' > lists/ip4
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv6' > lists/ip6
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].HostName' > lists/hosts

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Feed
