name: Update

on:
  workflow_dispatch:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "15 */6 * * *"

jobs:
  list-update:
    runs-on: ubuntu-24.04-arm

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Update Lists
      run: |
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv4' > feed/ipv4
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].IPv6' > feed/ipv6
          curl https://login.tailscale.com/derpmap/default | jq -r '.Regions[].Nodes[].HostName' > feed/hosts

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Update Feed
